### ISSUE TITLE
Docs: Criar novo readme

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-front#11]
# OVERVIEW

- Com o readme do back pronto, basta copia-lo para o repositório do front, mas com suas adaptações;

# TASKS

- [x] Criar o readme;
- [x] Adaptar as tecnologias;
- [x] Adaptar instruções de instalação;
- [x] Adaptar versões do sistema;
