### ISSUE TITLE
Style: Corrigir o css da página de login

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-front#19]
# OVERVIEW

- O header da página de login difere em espaçamento do topo em relação a página de cadastro, além dos próprios cards também estarem em posições diferentes;
- Também é interessante realizar algumas refatorações em relação ao código de estilização de maneira geral (uso do :deep() como na página de cadastro por exemplo);

# TASKS

- [ ] Corrigir o style do header;
- [ ] Corrigir o style do card;
- [ ] Refatorações gerais necessárias (inclui verificar a gambiarra do header do card);
