### ISSUE TITLE
Refactor: Adicionar aliases das pastas

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-front#24]
# OVERVIEW

- Adicionar aliases (ver package.json do backend) as pastas do frontend e refatorar os imports ao longo do código para usá-los;

# TASKS

- [ ] Adicionar alias da pasta src;
- [ ] Adicionar alias da pasta assets;
- [ ] Adicionar alias da pasta pages;
- [ ] Adicionar alias da pasta router;
- [ ] Adicionar alias da pasta store;
- [ ] Adicionar alias da pasta utils;
- [ ] Refatorar os imports do código para usar os aliases;
